Meteor.startup(function () {
  if (Courses.find().count() === 0) {
    Courses.insert({code: 'CSEN 615', name: 'Semi-Structured Data and the Web ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 901', name: 'Introduction to Artificial Intelligence', faculty: 'MET'});
    Courses.insert({code: 'CSEN 903', name: 'Advanced Computer Lab', faculty: 'MET'});
    Courses.insert({code: 'CSEN 905', name: 'Mobile and Pervasive Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 909', name: 'Human Computer Interaction (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 910', name: 'Sensor Networks (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 911', name: 'Data Mining', faculty: 'MET'});
    Courses.insert({code: 'CSEN 912', name: 'Multi-Paradigm Optimization (Elective)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 913', name: 'Special Topics in Multi-disciplinary optimization', faculty: 'MET'});
    Courses.insert({code: 'CSEN 914', name: 'Advanced Software Engineering Lab: Open Source Development', faculty: 'MET'});
    Courses.insert({code: 'CSEN 915', name: 'Semi-Structured Data and the Web ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 916', name: 'Multi/Many-Core Processors Programming & Architecture', faculty: 'MET'});
    Courses.insert({code: 'CSEN 917', name: 'Multi-Agent Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 919', name: 'Designing Mobile Technologies (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 920', name: 'Semantics of Programing Languages (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 921', name: 'Parallel Computing ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1004', name: 'Fuzzy Logic Control and Hybrid Systems ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1046', name: 'Intelligence in Wireless Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1048', name: 'Mathematical Optimization', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1056', name: 'Modern Communication Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1057', name: 'The Semantic IoT', faculty: 'MET'});
    Courses.insert({code: 'DMET 901', name: 'Computer Vision', faculty: 'MET'});
    Courses.insert({code: 'DMET 902', name: 'Advanced Video Processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 904', name: 'Advanced Media Lab', faculty: 'MET'});
    Courses.insert({code: 'DMET 905', name: 'VoIP Technology (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 801', name: 'Bachelor Thesis', faculty: 'MET'});
    Courses.insert({code: 'CSEN 301', name: 'Data Structures and Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 505', name: 'Introduction to Data Base Systems', faculty: 'MET'});
    Courses.insert({code: 'EDPT 301', name: 'Engineering Drawing and Projection', faculty: 'MET'});
    Courses.insert({code: 'ELCT 301', name: 'Electric Circuits I', faculty: 'MET'});
    Courses.insert({code: 'HUMA 301', name: 'German Language III', faculty: 'MET'});
    Courses.insert({code: 'HUMA 302', name: 'Communication & Presentation Skills ', faculty: 'MET'});
    Courses.insert({code: 'MATH 301', name: 'Mathematics III', faculty: 'MET'});
    Courses.insert({code: 'MATH 305', name: 'Mathematics for Business Informatics', faculty: 'MET'});
    Courses.insert({code: 'PHYS 301', name: 'Physics III', faculty: 'MET'});
    Courses.insert({code: 'CSEN 501', name: 'Data Bases I', faculty: 'MET'});
    Courses.insert({code: 'CSEN 502', name: 'Theory of Computation', faculty: 'MET'});
    Courses.insert({code: 'CSEN 503', name: 'Introduction to Communication Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 507', name: 'Theory of Computation', faculty: 'MET'});
    Courses.insert({code: 'CSEN 605', name: 'Digital System Design', faculty: 'MET'});
    Courses.insert({code: 'DMET 501', name: 'Introduction to Media Engineering', faculty: 'MET'});
    Courses.insert({code: 'DMET 502', name: 'Computer Graphics', faculty: 'MET'});
    Courses.insert({code: 'DMET 610', name: 'Introduction to Networks', faculty: 'MET'});
    Courses.insert({code: 'MATH 501', name: 'Mathematics V (Discrete Math)', faculty: 'MET'});
    Courses.insert({code: 'NETW 503', name: 'Internet', faculty: 'MET'});
    Courses.insert({code: 'CSEN 601', name: 'Computer System Architecture', faculty: 'MET'});
    Courses.insert({code: 'CSEN 602', name: 'Operating Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 603', name: 'Software Engineering', faculty: 'MET'});
    Courses.insert({code: 'CSEN 604', name: 'Data Bases II', faculty: 'MET'});
    Courses.insert({code: 'DMET 601', name: 'Web Technologies and Usability', faculty: 'MET'});
    Courses.insert({code: 'DMET 602', name: 'Media and Network lab', faculty: 'MET'});
    Courses.insert({code: 'DMET 603', name: 'Digital Signal Processing', faculty: 'MET'});
    Courses.insert({code: 'COMM 602', name: 'Digital Signal Processing', faculty: 'MET'});
    Courses.insert({code: 'HUMA 601', name: 'Introduction to Management', faculty: 'MET'});
    Courses.insert({code: 'CSEN 906', name: 'Constraint Programming (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 907', name: 'Knowledge Representation and Reasoning (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1001', name: 'Computer and Network Security', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1002', name: 'Advanced Computer Lab', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1003', name: 'Compiler', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1005', name: 'Neural Networks (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1008', name: 'Seminar on Context-aware Services for Mobile Users', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1008', name: 'Seminar on Intelligent Transportation Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1008', name: 'Seminar on Crowd Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1008', name: 'Seminar on Spatio-Temporal Reasoning', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1009', name: 'Seminar on Context and Contextual Reasoning', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1009', name: 'Seminar on Self Reference', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1009', name: 'Seminar on Sustainable Transportation', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1009', name: 'Seminar on Naturally Inspired Computing ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1010', name: 'Seminar on Wireless Sensor Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1010', name: 'Seminar on Techno-economic problems in Renewable Energy', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1010', name: 'Seminar on Optimization under Uncertainty', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1010', name: 'Seminar on Constraint Reasoning ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1011', name: 'Seminar on Organic Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1011', name: 'Seminar on Existing modeling frameworks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1011', name: 'Seminar on Multiagent Systems ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1011', name: 'Seminar on Advanced Computer Architecture', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1012', name: 'Seminar on Sensor Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1012', name: 'Seminar on Vehicular ad hoc networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1012', name: 'Seminar on Methods for composition', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1012', name: 'Seminar on Cybernetics', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1013', name: 'Seminar Multi-Core & High Performance Computing ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1013', name: 'Seminar on Applications of Constraint Technology', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1013', name: 'Seminar on Theory and Implementation of Type Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1013', name: 'Seminar on Analyzing and studying emerging multimedia systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1014', name: 'Seminar on Formal Ontology', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1014', name: 'Seminar on Wikipedia Mining', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1014', name: 'Seminar on Cloud Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1015', name: 'Seminar on Energy Aware Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1017', name: 'Introduction to Model Checking and Temporal Logics (Elective)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1018', name: 'Ubiquitous Computing (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1020', name: 'Information Storage and Management in Cloud Computing (Elective)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1020', name: 'Information Storage and Management in Cloud Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1022', name: 'Machine Learning', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1026', name: 'Embedded Real-Time Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1027', name: 'Seminar in Biologically inspired computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1028', name: 'Seminar in Selected topics in Computer science', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1030', name: 'Seminar on GPU Computing Applications', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1031', name: 'Seminar on Object-Oriented Design Patterns', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1032', name: 'Seminar in Arabic Natural Language Processing: Challenges and Solutions', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1033', name: 'Seminar in Topics and applications in cryptography', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1034', name: 'Seminar on Rational Belief Change', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1036', name: 'Seminar in Herculean Tasks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1037', name: 'Seminar in Selected topics in Computer science ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1038', name: 'Advanced Data Structures and Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1039', name: 'Biologically Inspired Optimization', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1040', name: 'Selected Topics in advanced Embedded Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1041', name: 'Seminar on Crowdsourcing and Human-Computation Techniques', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1042', name: 'Seminar in Ubiquitous and Wearable Computing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1044', name: 'Seminar on Cognitive Robotics', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1045', name: 'Seminar in Wireless Multihop Ad Hoc Networks', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1047', name: 'Seminar in Natural Language Processing (NLP)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1051', name: 'Seminar in Evolutionary Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1052', name: 'Seminar in Combinatorics', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1053', name: 'Seminar on Cloud Computing and Virtualization', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1054', name: 'Seminar on Arabic Natural Language Processing', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1055', name: 'A seminar on general topics in software engineering', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1058', name: 'Mobile Apps Dev', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1059', name: 'Advanced Web Dev: Concepts, Architecture & Applications ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1060', name: 'Advanced UI Dev: Markup, Scripting & Optimization', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1061', name: 'An Introduction to Data Science', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1062', name: 'Seminar in Internet of Things ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1063', name: 'Seminar on Computation and Cognition', faculty: 'MET'});
    Courses.insert({code: 'CSEN 1065', name: 'Seminar on Advanced Topics in Software Development', faculty: 'MET'});
    Courses.insert({code: 'DMET 1001', name: 'Image Processing (Elective for CSEN)', faculty: 'MET'});
    Courses.insert({code: 'DMET 1002', name: 'Advanced Media Lab', faculty: 'MET'});
    Courses.insert({code: 'DMET 1003', name: 'Audio and Acoustics', faculty: 'MET'});
    Courses.insert({code: 'DMET 1005', name: 'Digital Watermarking (Elective for DMET)', faculty: 'MET'});
    Courses.insert({code: 'DMET 1007', name: 'Digital Broadcasting System', faculty: 'MET'});
    Courses.insert({code: 'DMET 1007', name: 'Digital Broadcasting Systems (Elective for DMET)', faculty: 'MET'});
    Courses.insert({code: 'DMET 1008', name: 'Seminar on Computer-Aided Design and Technology', faculty: 'MET'});
    Courses.insert({code: 'DMET 1008', name: 'Seminar on Graphics and Image File Formats', faculty: 'MET'});
    Courses.insert({code: 'DMET 1008', name: 'Seminar on Mobile World Browsers 2.0', faculty: 'MET'});
    Courses.insert({code: 'DMET 1008', name: 'Seminar on Human Computer Interaction', faculty: 'MET'});
    Courses.insert({code: 'DMET 1009', name: 'Seminar on Collective Intelligence', faculty: 'MET'});
    Courses.insert({code: 'DMET 1009', name: 'Seminar on Advanced Topics on Video Coding/Processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1009', name: 'Seminar on Advanced Research in Human-Computer Interaction', faculty: 'MET'});
    Courses.insert({code: 'DMET 1009', name: 'Seminar on Digital Audio Effects Processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1010', name: 'Seminar on  Cross-Cultural Topics in Human-Computer Interaction', faculty: 'MET'});
    Courses.insert({code: 'DMET 1010', name: 'Seminar on Advanced Topics in Human-Computer Interaction', faculty: 'MET'});
    Courses.insert({code: 'DMET 1010', name: 'Seminar on Computer Generated Imagery with Maya', faculty: 'MET'});
    Courses.insert({code: 'DMET 1010', name: 'Seminar on Hypertext ', faculty: 'MET'});
    Courses.insert({code: 'DMET 1011', name: 'Seminar on Handheld Augmented Reality', faculty: 'MET'});
    Courses.insert({code: 'DMET 1011', name: 'Seminar on the Emerging High Efficiency Video Coding Standard', faculty: 'MET'});
    Courses.insert({code: 'DMET 1015', name: 'HCI for Startups', faculty: 'MET'});
    Courses.insert({code: 'DMET 1016', name: 'Multimedia and data transmission over wireless networks', faculty: 'MET'});
    Courses.insert({code: 'DMET 1017', name: 'Dialogue Systems', faculty: 'MET'});
    Courses.insert({code: 'DMET 1035', name: 'Seminar in Emerging Video Technologies', faculty: 'MET'});
    Courses.insert({code: 'DMET 1036', name: 'Seminar in Bio and Wearable Sensors: Challenges & Research Opportunities', faculty: 'MET'});
    Courses.insert({code: 'DMET 1037', name: 'Topics in Visual Computing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1038', name: 'Seminar on Photogrammetry', faculty: 'MET'});
    Courses.insert({code: 'DMET 1039', name: 'Seminar in Computational Intelligence for Adaptive Image Processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1040', name: 'Seminar in Brain Computer Interfaces ', faculty: 'MET'});
    Courses.insert({code: 'DMET 1041', name: 'Seminar in Latest Advances in Audio & Acoustic Signal Processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1041', name: 'Seminar in Latest advances in audio and acoustic signal processing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1042', name: 'Fundamentals of VoIP ', faculty: 'MET'});
    Courses.insert({code: 'DMET 1043', name: 'Seminar in Modeling in Space', faculty: 'MET'});
    Courses.insert({code: 'DMET 1044', name: 'Seminar on Interfaces and Systems for the Classroom', faculty: 'MET'});
    Courses.insert({code: 'DMET 1045', name: 'Seminar in Using Body Gestures In Driving Interaction', faculty: 'MET'});
    Courses.insert({code: 'DMET 1046', name: 'Seminar in Selected Topics in Multimedia Communications', faculty: 'MET'});
    Courses.insert({code: 'DMET 1048', name: 'Seminar in Digital compositing', faculty: 'MET'});
    Courses.insert({code: 'DMET 1049', name: 'Seminar in Gesture Design and Formal Evaluation', faculty: 'MET'});
    Courses.insert({code: 'ELCT 1002', name: 'Systems-on-a-Chip (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'HUMA 1001', name: 'Project Management ', faculty: 'MET'});
    Courses.insert({code: 'NETW 1001', name: 'Sensor Networks ', faculty: 'MET'});
    Courses.insert({code: 'NETW 1003', name: 'Network Planning (Elective MET) ', faculty: 'MET'});
    Courses.insert({code: 'NETW 1011', name: 'Intelligent Transportation Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 401', name: 'Computer Programming Lab', faculty: 'MET'});
    Courses.insert({code: 'CSEN 402', name: 'Computer Organization and System Programming ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 403', name: 'Concepts of Programming languages', faculty: 'MET'});
    Courses.insert({code: 'CSEN 404', name: 'Introduction to Networks', faculty: 'MET'});
    Courses.insert({code: 'DMET 603', name: 'Media Design', faculty: 'MET'});
    Courses.insert({code: 'COMM 401', name: 'Signal and System Theory', faculty: 'MET'});
    Courses.insert({code: 'ELCT 401', name: 'Electric Circuits II', faculty: 'MET'});
    Courses.insert({code: 'HUMA 402', name: 'German Language IV', faculty: 'MET'});
    Courses.insert({code: 'HUMA 402', name: 'Research Paper Writing ', faculty: 'MET'});
    Courses.insert({code: 'MATH 401', name: 'Mathematics IV (Prob. a. Statistics)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 001', name: 'Preparatory Computer Science', faculty: 'MET'});
    Courses.insert({code: 'CSEN 101', name: 'Introduction to Computer Science', faculty: 'MET'});
    Courses.insert({code: 'CSEN 102', name: 'Introduction to Computer Science - IG', faculty: 'MET'});
    Courses.insert({code: 'CSEN 102', name: 'Introduction to Computer Science', faculty: 'MET'});
    Courses.insert({code: 'CSIS 101', name: 'Introduction to Computer Science I', faculty: 'MET'});
    Courses.insert({code: 'CSIS 101', name: 'Introduction to Computer Science 1 - IG', faculty: 'MET'});
    Courses.insert({code: 'CSIS 104', name: 'Introduction to Computer Science - IG', faculty: 'MET'});
    Courses.insert({code: 'CSIS 104', name: 'Introduction to Computer Science ', faculty: 'MET'});
    Courses.insert({code: 'CHEM 101', name: 'Chemistry I', faculty: 'MET'});
    Courses.insert({code: 'HUMA 101', name: 'German Language I', faculty: 'MET'});
    Courses.insert({code: 'HUMA 102', name: 'Academic English', faculty: 'MET'});
    Courses.insert({code: 'HUMA 103', name: 'Academic Study Skills', faculty: 'MET'});
    Courses.insert({code: 'MATH 103', name: 'Mathematics I', faculty: 'MET'});
    Courses.insert({code: 'PHYS 102', name: 'Physics I', faculty: 'MET'});
    Courses.insert({code: 'CSEN 310', name: 'Data Structures and Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 701', name: 'Embedded Systems', faculty: 'MET'});
    Courses.insert({code: 'CSEN 702', name: 'Microprocessors', faculty: 'MET'});
    Courses.insert({code: 'CSEN 703', name: 'Analysis and Design of Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 704', name: 'Advanced computer lab', faculty: 'MET'});
    Courses.insert({code: 'CSEN 707', name: 'Analysis and design of Algorithms', faculty: 'MET'});
    Courses.insert({code: 'CSEN 909', name: 'Human Computer Interaction (Elective for MET)', faculty: 'MET'});
    Courses.insert({code: 'CSEN 911', name: 'Data Mining', faculty: 'MET'});
    Courses.insert({code: 'DMET 502', name: 'Computer Graphics', faculty: 'MET'});
    Courses.insert({code: 'DMET 701', name: 'Computer Graphics', faculty: 'MET'});
    Courses.insert({code: 'DMET 702', name: 'Visualization and Animation', faculty: 'MET'});
    Courses.insert({code: 'DMET 703', name: 'Video and Audio Technology', faculty: 'MET'});
    Courses.insert({code: 'DMET 704', name: 'Multimedia & Networking', faculty: 'MET'});
    Courses.insert({code: 'DMET 706', name: 'Advanced Media Lab', faculty: 'MET'});
    Courses.insert({code: 'BINF 711', name: 'Information Security ', faculty: 'MET'});
    Courses.insert({code: 'CSEN 202', name: 'Introduction to Computer Programming - IG', faculty: 'MET'});
    Courses.insert({code: 'CSEN 202', name: 'Introduction to Computer Programming', faculty: 'MET'});
    Courses.insert({code: 'CSIS 202', name: 'Introduction To Computer Science II', faculty: 'MET'});
    Courses.insert({code: 'CSIS 202', name: 'Introduction To Computer Science II', faculty: 'MET'});
    Courses.insert({code: 'CSIS 202', name: 'Introduction To Computer Science II - IG', faculty: 'MET'});
    Courses.insert({code: 'EDPT 201', name: 'Production Technology', faculty: 'MET'});
    Courses.insert({code: 'ELCT 201', name: 'Digital Logic Design', faculty: 'MET'});
    Courses.insert({code: 'HUMA 201', name: 'German Language II', faculty: 'MET'});
    Courses.insert({code: 'HUMA 202', name: 'Critical Thinking & Scientific Methodology', faculty: 'MET'});
    Courses.insert({code: 'MATH 203', name: 'Mathematics II', faculty: 'MET'});
    Courses.insert({code: 'PHYS 202', name: 'Physics II', faculty: 'MET'});
  }
});
